### ISSUE TITLE
feat(linter): eslint v9 recommended rules

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#1191]
`https://github.com/eslint/eslint/issues/17596`

```[tasklist]
### Tasks
- [x] no-constant-binary-expression - reports possible errors
- [x] no-empty-static-block - similar to no-empty, which is already in eslint:recommended #1543
- [ ] no-unused-private-class-members - reports possible errors
```
Note: we have a separate issue for no-new-native-nonconstructor `(https://github.com/eslint/eslint/issues/17446)`

**Comment by Boshen** [comment]
FYI @camc314

**Comment by Boshen** [comment]
All done!
