### ISSUE TITLE
Automate the linter rules list

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#2020]
The process of tracking implemented and unimplemented rules should be automated.

A new task should be added to `tasks/`. It will pull all our supported plugins from their source, compare them against our implemented rules, and generate a markdown file with a tracking list.

We can initiate the task by only pulling from https://raw.githubusercontent.com/eslint/eslint/main/packages/js/src/configs/eslint-all.js and then expand to other plugins with follow up PRs.

eslint-all.js is a JS file but we can use oxc's parser to parse and extract all the rules.

**Comment by Boshen** [comment]
Initial set of code has been merged: https://github.com/oxc-project/oxc/pull/2068

Pasting my reply here as well.

I think the next PR should pull in all the other plugins.

> If it is better to generate a file in Rust code, where should I output to?

What I have in mind is trigger the task in CI and update GitHub issues.

> Which one do you expect?

If we are going to update GitHub issues, it'll be easier with "for 1 plugin by specifying name
".

> Do we need a blacklist?(and how do I know the list?)

I think so, for example we won't be able to implement type checking lint rules. We'll need to hard code it I guess.

**Comment by Boshen** [comment]
@leaysgur is coordinating the tasks.

**Comment by leaysgur** [comment]
OK, I will add rough design docs and a roadmap like todo list later.
(For anyone who is interested in helping. 🙌)

**Comment by leaysgur** [comment]
## What to make

For all rules of all plugins supported by `oxlint`, visualize their implementation progress with automatic workflows.

- A task that retrieves all rules for each plugin, compares them with the implementation status (file exists or not) and outputs the diff results.
- A task reflects its results to the umbrella issues of each plugin.
- GitHub Actions that are triggered by a merge to `main` of the PR and execute these tasks.

## Details
### Task to retrieve progress
- `cargo run -p lint_rules {PLUGIN_NAME}`
- Get a list of rules for each plugin(A)
  - Some may be all list, some need only recommended
  - The rules are in a JS configuration file, so parse with AST and enumerate
  - Exclude rules that are not supported by `oxlint`
- Compare with the list of implemented rules(= files or directories)(B) 
  - B in A ? ✅
  - (Some may be in B but not in A...?)
- Formatted into a Markdown TODO list

### Task to reflect progress
- `GITHUB_TOKEN=XXX cargo run -p lint_rules {PLUGIN_NAME} --apply`
  - If `GITHUB_TOKEN` is not enough, need to prepare a PAT?
  - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
- Update umbrella issue comment for that plugin
  - Top comment is the best but there may be permission problems...?
  - Dedicated progress comments would be good too
- Marketplace actions may be usable, but just call one API is enough
  - https://github.com/peter-evans/create-or-update-comment/blob/b865fac7facb67bed02e0032aedefe6acf790c75/src/create-or-update- comment.ts#L175-L180
  - Comment IDs would be hard-coded
- Update contents
  - Title: {PLUGIN_NAME}
  - Updated at
  - TODO List
  - Notes?
    - Some may not be fully implemented, as implementation is determined by the presence of files

### GitHub Actions
- Triggered by PR merge+close
  - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull- request-merges
- Execute tasks for all supported plugins
- PRs that are not relevant to Linter rules should be ignored?
  - `contains(github.event.pull_request.labels.*.name, 'A-linter')`?
- Plugins not related to that PR should be ignored too
  - But it is not as simple as it seems, maybe?
  - If not, just updated time is updated

**Comment by leaysgur** [comment]
## TODOs

- [ ] Refactoring current code base(handle args, fix up files, filter unsupported rules, etc...) 👉🏻  @leaysgur 
- [ ] Implement each rules(fetch and parse AST)
  - [x] eslint
  - [ ] typescript
  - [ ] import
  - [ ] jsdoc
  - [ ] n
  - [ ] jsx_a11y
  - [ ] jest
  - [ ] unicorn
  - [ ] react
  - [ ] nextjs
  - [ ] react-perf
- [ ] Maintain unsupported rules list
  - [ ] eslint
  - [ ] typescript
  - [ ] import
  - [ ] jsdoc
  - [ ] n
  - [ ] jsx_a11y
  - [ ] jest
  - [ ] unicorn
  - [ ] react
  - [ ] nextjs
  - [ ] react-perf
- [ ] Implement issue update func by `--apply` flag
- [ ] Implement and test GitHub Actions workflow

If anyone is interested to help, feel free to ping me. 😉

**Comment by Boshen** [comment]
@leaysgur You may look at adding more plugin rules. I'll help out with making the list more informational tomorrow (or the day after).

**Comment by leaysgur** [comment]
OK. I will add the rules for other plugins. (maybe tomorrow 😴 ).

**Comment by Boshen** [comment]
@leaysgur yeah let's go with running some js code to get the list ... I was too naive about parsing js files 😭

**Comment by leaysgur** [comment]
I understand. 😓  (especially configuration file written in js...)

Therefore, I will restart with this PoC direction and submit another PR.

**Comment by Boshen** [comment]
@leaysgur is it possible to have some rule counters at the top of each table?

Something like, "implemented 4/20 all rules, 3/15 recommended rules"

**Comment by Boshen** [comment]
Does it make sense to omit all the deprecated rules?

**Comment by leaysgur** [comment]
🙆🏻‍♂️  I think I can handle all of them. I will try it.

**Comment by Boshen** [comment]
All completed. Thank you again @leaysgur !
