### ISSUE TITLE
Refactor playground

### ISSUE THREAD

**Issue by Dunqing** [oxc-project/oxc#3230]
## Overview

As more features are added I think a vanilla.js-based implementation would become more cumbersome and difficult to maintain. So we plan to refactor the playground based on `Vue` framework 

## Tasks

- [ ] Refactor playground based on `Vue` framework
- [ ] Replace the current CodeMirror editor with [Monaco](https://github.com/microsoft/monaco-editor).
- [ ] Support for transformer configuration editing. Learn more #2709 

## Possible Tasks

- Linter rules configuration
- ..

## Playground Design

Since we don't have a designer, we can't design a nice playground, but instead, maybe we can use [shadcn-vue](https://www.shadcn-vue.com/) and utility-first CSS framework for `UnoCSS` or `TailwindCSS` to help us build it quickly. Or ask AI at https://www.vue0.dev/

## Expected Outcome

By the end of this refactor, the OXC Playground should be more user-friendly and maintainable. The switch to Vue and Monaco should provide a better development experience.

## Reference
- https://github.com/sxzz/ast-explorer AST Explorer, Use Vue and [Monaco](https://github.com/microsoft/monaco-editor)
- https://play.swc.rs/ SWC Playground
- https://biomejs.dev/playground/ Biome Playground

**Comment by DonIsaac** [comment]
I've been spending a lot of time writing language services for Monaco for custom DSLs my company uses, I could help integrate an Oxc language service into Monaco

**Comment by Boshen** [comment]
Oh nice! I plan to create a new repo for the playground, stay tuned.
