### ISSUE TITLE
feat(linter): Support potentially dangerous fixes behind a `--fix-dangerously` flag

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#4211]
Some problems are potentially auto fixable, but doing so may be undesireable. In some cases, it could produce incorrect code. In other cases, it could change the behavior of applications.

ESLint handles this with [Rule Suggestions](https://eslint.org/docs/latest/use/core-concepts#rule-suggestions), which are made available to language servers but do not get applied via `--fix`.

Since the linter is mostly used as a CLI (oxlint), we need to support applying suggestions there too. I think we should do this with a `--fix-dangerously` flag.

## Tasks
> NOTE: only the first two tasks are prerequisites for #4179
- [ ] refactor(linter): update `FIx` to support suggestions
- [ ] feat(cli): add `--fix-dangerously` flag 
- [ ] feat(lsp): add command to apply suggestions

**Comment by Boshen** [comment]
Interesting, can you hold onto adding the flag and the command? I want to research and understand these first.

**Comment by DonIsaac** [comment]
Too late unfortunately, I've got a draft out already

**Comment by DonIsaac** [comment]
We may also want to support multiple suggestions for each diagnostic.
