### ISSUE TITLE
AST transfer milestone 1

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4294]
Intention is that I embark on Milestone 1 of AST transfer (see oxc-project/oxc#2409, https://github.com/oxc-project/backlog/issues/47) over next few weeks, with aim of merging a minimal first working version. Steps required:

* [x] oxc-project/oxc#4295
* [x] oxc-project/oxc#4296
* [x] oxc-project/oxc#4381
* [ ] Update existing AST transfer impl (#2457) to use that schema, instead of using [layout_inspect](https://github.com/overlookmotel/layout_inspect).
* [ ] Integrate into NodeJS APIs `parseSync` and `parseAsync` - I suggest only enabled for now if user passes an option `experimentalRawTransfer: true`.
* [ ] Optimizations(probably next milestone)
* [ ] oxc-project/backlog#122 (moved to next milestone)

NB: None of the above includes any breaking changes for consumers of Oxc's Rust crates. The only breaking change is in API of NPM package `oxc-parser`.

**Comment by Boshen** [comment]
All done, with future tracking issues.
