### ISSUE TITLE
regular_expression: Support ES2025 proposal-duplicate-named-capturing-groups

### ISSUE THREAD

**Issue by leaysgur** [oxc-project/oxc#6358]
> https://github.com/tc39/proposal-duplicate-named-capturing-groups

Spec text is not updated yet, ongoing PR may be helpful. 👉🏻 https://github.com/tc39/ecma262/pull/2721

For now, `/(?<a>.)(?<a>.)/` is invalid syntax, name `a` is duplicated.

With this change, we can use the same name if they are splitted by `|` and in the same `Disjunction` like `/(?<a>.)|(?<a>.)/`.

But it still not allowed in some cases like `/(?<n>|(?<n>))/`, `/(?<n>(?<n>)|)/`, `/((?<n>)|(?<n>))(?<n>)/`, etc...

You need to track nesting level and `|` to mange scope.

### TODOs

- [ ] Update count capturing parens logic to allow duplicates in certain cases
  - https://github.com/oxc-project/oxc/blob/aa7718ab7bf0544b21564658a919307022f8824a/crates/oxc_regular_expression/src/body_parser/state.rs#L51
  - No need to change parser main logic
- [ ] Update README
  - https://github.com/oxc-project/oxc/blob/aa7718ab7bf0544b21564658a919307022f8824a/crates/oxc_regular_expression/README.md
- [ ] Update local tests
  - https://github.com/oxc-project/oxc/blob/aa7718ab7bf0544b21564658a919307022f8824a/crates/oxc_regular_expression/src/body_parser/mod.rs
- [ ] Enable conformance tests
  - https://github.com/oxc-project/oxc/blob/aa7718ab7bf0544b21564658a919307022f8824a/tasks/coverage/src/test262/mod.rs#L103-L104

**Comment by preyneyv** [comment]
I'd like to take a stab at this!

**Comment by Boshen** [comment]
@preyneyv You may continue with https://github.com/oxc-project/oxc/pull/6847

**Comment by leaysgur** [comment]
#15045 (Thanks Claude 🤖)
