### ISSUE TITLE
editor: Lint new/unsaved files

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#7455]
## Story
As a developer, I want files linted as I type so that I can get instantaneous feedback as I code

## Context
We support an `oxc.lint.run` option, where linting runs either when a user saves (`onSave`) or as they type (`onType`). However, the linter only ever reads files from the file system. Files with unsaved changes will therefore not be linted correctly. We need to be able to pass the current in-memory file contents to the linter.

## Tasks
- [ ] linter: Add `fs` abstraction to linter
- [ ] linter: Make `ModuleCache` mutable over already-resolved modules
- [ ] editor: read files from editor text model instead of file system

## Acceptance Criteria
- Parse errors encountered before the user has saved (because they're actively typing) should not be reported as diagnostics.
- When using import plugin, only the file that was changed should be re-linted. Do not re-build the module graph for all files each time.

**Comment by Boshen** [comment]
I think this is not a good idea, and is too complicated to implement.
