### ISSUE TITLE
editor: Delightful auto-fix support

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxc#7456]
## Story
As a user, I want to automatically apply auto fixes supplied by my editor so that I don't have to apply them manually.

## Tasks
- [ ] editor: add `Fix all auto-fixable problems (file)` command
- [ ] editor: add `Fix all auto-fixable problems (workspace)` command
- [ ] editor: support "fix this problem" code suggestion

**Comment by nrayburn-tech** [comment]
"fix this problem" should be completed in VS Code and JetBrains.
"Fix all auto-fixable problems (file)" should be completed for VS Code in https://github.com/oxc-project/oxc/pull/7672.
