### ISSUE TITLE
☂️ Transpiler / Transformer

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#974]
## Contribution Instructions

The implementation is in `crates/oxc_transformer`.

To get started, take a look at the [previous implementations](https://github.com/web-infra-dev/oxc/pulls?q=is%3Apr+is%3Aclosed+label%3AA-transformer).

The integrations tests are located in `tasks/transform_conformance/src/lib.rs`,
Run it with `just watch 'run -p oxc_transform_conformance'` or with a filter `just watch "run -p oxc_transform_conformance -- --filter type-arguments"`.

---
## Tasks

- [ ] https://github.com/web-infra-dev/oxc/issues/979
- [x] https://github.com/web-infra-dev/oxc/pull/1001
- [x] https://github.com/web-infra-dev/oxc/issues/999
- [x] Fix transformer benchmark because it is transforming the already transformed AST https://github.com/web-infra-dev/oxc/pull/998

## Third Party Plugins

- [ ] https://www.npmjs.com/package/babel-plugin-import

## Feature list

Legend:
* [Syntax] means this is a syntax plugin, no code is required because it is supported by the parser.
* [Regex] means this is a regex transform, which is not supported.
* [Codegen] means the code generator is responsible for the feature.

## @babel/preset-react

- [ ] @babel/plugin-transform-react-jsx

## [@babel/preset-typescript](https://babel.dev/docs/babel-preset-typescript)

- [ ] @babel/plugin-transform-typescript

### ES2024

- [ ] [Regex] unicode-sets-regex

### ES2023

Does not have any features.

### ES2022

- [ ] class-properties
- [x] class-static-block https://github.com/web-infra-dev/oxc/pull/962
- [ ] private-methods
- [ ] private-property-in-object
- [x] [Syntax] syntax-top-level-await

### ES2021

- [ ] logical-assignment-operators https://github.com/web-infra-dev/oxc/pull/923
- [x] [Syntax] numeric-separator

### ES2020

- [ ] dynamic-import
- [ ] export-namespace-from
- [ ] nullish-coalescing-operator https://github.com/web-infra-dev/oxc/pull/1004
- [ ] optional-chaining
- [x] [Syntax] syntax-bigint
- [x] [Syntax] syntax-dynamic-import
- [x] [Syntax] syntax-import-meta

### ES2019

- [x] optional-catch-binding
- [x] [Codegen] json-strings

### ES2018

- [ ] async-generator-functions
- [ ] object-rest-spread
- [ ] [Regex] unicode-property-regex
- [ ] [Regex] dotall-regex
- [ ] [Regex] named-capturing-groups-regex

### ES2017

- [ ] async-to-generator

### ES2016

- [x] exponentiation-operator https://github.com/web-infra-dev/oxc/pull/996

### ES2015

- [ ] arrow-functions
- [ ] block-scoping
- [ ] classes
- [ ] computed-properties
- [ ] destructuring
- [ ] duplicate-keys
- [ ] for-of
- [ ] function-name
- [ ] instanceof
- [ ] literals
- [ ] new-target
- [ ] object-super
- [ ] parameters
- [x] shorthand-properties https://github.com/web-infra-dev/oxc/pull/960
- [ ] spread
- [x] sticky-regex https://github.com/web-infra-dev/oxc/pull/968
- [ ] template-literals
- [ ] typeof-symbol
- [ ] [Regex] unicode-escapes
- [ ] [Regex] unicode-regex

**Comment by Boshen** [comment]
I'm going to start with `https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-nullish-coalescing-operator/src/index.ts`, which is simple but requires adding new variables to the scope.

**Comment by rzvxa** [comment]
@Boshen Is there any reason why some of these parts aren't checked while having an implementation in the transformer? If it is simply out dated let me know to take over it and keep in sync with our progress.

**Comment by Boshen** [comment]
Closing in favor of the redo in https://github.com/oxc-project/oxc/issues/2859
